### ISSUE TITLE
DESCRIPTION

### ISSUE THREAD

**Issue by muschellij2** [avalcarcel9/rtapas#1]
aliviateR and badgecreatr should not be in remotes adn not imported as they are not used in the NAMESPACE at all.

**Comment by muschellij2** [comment]
Also, where is `bookdown` being used.  Pretty heavy suggested package.

**Comment by avalcarcel9** [comment]
aliviateR is used in the `tapas_data` function. `badgecreatr` is a dependency that was causing some issues so I added it to resolve some building complications. `bookdown` was originally used for the vignettes. Packages have been updated so stability is no longer problem and I've updated the package to reflect this issue.
