### ISSUE TITLE
Update to Neuroc

### ISSUE THREAD

**Issue by muschellij2** [avalcarcel9/rtapas#7]
Can you submit this update to neuroconductor?  It's currently seemingly many versions old.  See https://neuroconductor.org/package/rtapas.  

> You can now update any of your Neuroconductor packages without resubmitting the package, or even visiting the Neuroconductor page. In order to do so, you will need to use the keyword submit_package_release or neuroc_release in a GitHub commit. Our cron jobs will pick up the submission and we will start processing the update right away.

**Comment by avalcarcel9** [comment]
Just resubmit using the keywords! Closing the issue. reach out if it doesn't submit for some reason.
